services:
  nginx:
    build: ./iyad-portfolio/frontend
    container_name: portfolio_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./iyad-portfolio/backend
    container_name: portfolio_backend
    restart: always
    expose:
      - "5000"